feat: add Junit Report, commitizen
Add steps in pipeline to Junit report, commitizen to standarize commits

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,7 +27,7 @@ jobs:
       - run: npx playwright install-deps
 
       - name: Run Playwright tests 
-        run: PLAYWRIGHT_HTML_REPORT=report npx playwright test --reporter=html,junit
+        run: PLAYWRIGHT_HTML_REPORT=report PLAYWRIGHT_JUNIT_OUTPUT_NAME=report/results.xml npx playwright test --reporter=html,junit
 
       - uses: actions/upload-artifact@v3
         if: always()
@@ -42,3 +42,17 @@ jobs:
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ${{ github.workspace }}/report/
+
+      # Upload xml as artifact
+      - uses: actions/upload-artifact@v3
+        with:
+          name: java-junit
+          path: ${{ github.workspace }}/report/results.xml
+
+      - name: Test Report Junit
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Junit Tests           # Name of the check run which will be created
+          path: ${{ github.workspace }}/report/*.xml     # Path to test results
+          reporter: java-junit       # Format of test results
